# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c684917160ba5466fa88a74fabb7f7cb624fb6c9daf6c63c7ee429f3855ff72dd29e79f96d4c42a35e552e19cdef55ffcdb13a55547e723729c0b176bdcc0655

test:
  secret_key_base: 5fa3637ea0aa48cabdb6e79aa8c14de50c50e775c397491e82225f4e342a1e454ee7320232d08a07113da4dd5587c738f5c2f98974ea95e7130f7b8247c5c4e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
